Update action.yml

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -30,16 +30,16 @@ runs:
         branch_name="${{ inputs.branch-name }}"
         commit_id="${{ inputs.commit-hash }}"
 
-        if ! git rev-parse --quiet --verify $commit_id; then
+        if ! $(git rev-parse --quiet --verify $commit_id); then
           echo "valid_commit=false" >> $GITHUB_OUTPUT
           echo "Invalid commit hash: \`$commit_id\`"
         else
           # Verify if the commit is on the specified branch
-          if ! git merge-base --is-ancestor $commit_id HEAD; then
-            echo "valid_commit=false" >> $GITHUB_OUTPUT
-            echo "Commit \`$commit_id\` is not found on the branch \`$branch_name\`"
-          else
+          if $(git merge-base --is-ancestor $commit_id HEAD); then
             echo "valid_commit=true" >> $GITHUB_OUTPUT
             echo "Commit \`$commit_id\` is valid and found on the branch \`$branch_name\`"
+          else
+            echo "valid_commit=false" >> $GITHUB_OUTPUT
+            echo "Commit \`$commit_id\` is not found on the branch \`$branch_name\`"
           fi
         fi
